name: Release Alpha Module

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'alpha/*'

jobs:
  call-template:
    uses: matheusmazzoni/test-semantic-version/.github/workflows/release.yml@main
    with:
      module_name: "alpha"
