name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'alpha/*'

env:
  MODULE_NAME: alpha

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Update .releaserc.json with Module Name
        run: |
          sed -i 's/"module_name"/"'$MODULE_NAME'"/g' .releaserc.json.tpl
          cp .releaserc.json.tpl $MODULE_NAME/.releaserc.json

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: ./${{ env.MODULE_NAME }}
          tag_format: ${{ env.MODULE_NAME }}_${version}
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
