name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'alpha/*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Update .releaserc.json with Module Name
        run: |
          MODULE_NAME=${{ env.moduleName }}
          jq '.tagFormat = "alpha_${version}"' .releaserc.json > temp.json && mv temp.json .releaserc.json

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        working-directory: ./alpha
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
