name: Release Alpha Module

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'alpha/*'

env:
  module_name: alpha
jobs:
  call-template:
    uses: matheusmazzoni/test-semantic-version/.github/workflows/release.yaml@main
    with:
      module_name: "alpha"
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}