name: Reusable Release Workflow

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
    secrets:
      SEMANTIC_RELEASE_TOKEN:
        required: true

permissions:
  contents: read
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
      
      - name: Update .releaserc.json with Module Name
        run: |
          export MODULE_NAME=${{ inputs.module_name }}
          sed -i 's/module_name/'$MODULE_NAME'/g' .releaserc.json.tpl 
          cp .releaserc.json.tpl $MODULE_NAME/.releaserc.json

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: ./${{ inputs.module_name }}
          tag_format: ${{ inputs.module_name }}_${version}
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
